### PR TITLE
Add an SVD for the ESP32-S2

### PR DESCRIPTION
**Pull request by jessebraham**
This adds the first version of the SVD for the ESP32-S2. I have done a preliminary review of the file but was hoping to get some more eyes on this before merging into `main`.

CC @aykevl @georgik @mabezdev

### CODE REVIEW

**Comment by aykevl** [comment]
Here are some remarks after quickly looking into it:

* The SVD file says the device doesn't have an FPU. Is this correct?
* No interrupts are listed in the SVD file: #6.
* Is there any reason you've switched to a dash in the device name (`ESP32C3` -> `ESP32-C3`)? Not a big issue, but it needs a small change in TinyGo because basically every other chip family we have some support for doesn't have such a dash.
* It would be useful to include the `groupName` tag. Right now there is UART0, and UART1 which derives from UART0, but there is no way to know the base name (UART) without some heuristics. As an example, see: https://github.com/posborne/cmsis-svd/blob/8ac69ea17f3a8f/data/Nordic/nrf51.svd#L5145

I haven't looked very deeply though. I don't have and ESP32-S2, I plan on focusing on the ESP32-C3 first.

**Comment by jessebraham** [comment]
Thank you @aykevl for taking a look at this, I appreciate the effort!

> The SVD file says the device doesn't have an FPU. Is this correct?

I believe this is correct; I don't see any mention of one in the Technical Reference Manual. @igrr are you able to confirm this please?


> No interrupts are listed in the SVD file: <interrupt> sections in peripherals missing #6.

These will be coming soon-ish I hope. The interrupts are in a different format from the register information, so I need to add this feature to the SVD generator still.


> Is there any reason you've switched to a dash in the device name (ESP32C3 -> ESP32-C3)? Not a big issue, but it needs a small change in TinyGo because basically every other chip family we have some support for doesn't have such a dash.

This was just to be consistent with Espressif's naming conventions. I didn't encounter any issues with `svd2rust` regarding this so I didn't give it much thought, sorry about that.


> It would be useful to include the groupName tag. For example: right now there is UART0, and UART1 which derives from UART0, but there is no way to know the base name (UART) without some heuristics. As an example how this works in a different SVD file, see: https://github.com/posborne/cmsis-svd/blob/8ac69ea17f3a8f/data/Nordic/nrf51.svd#L5145 (the Nordic SVD files are very well structured so IMHO can be used as an example).

Thank you for this suggestion, I will look into this. Shouldn't be difficult to add.


> (Off-topic: very much looking forward to an SVD file for the ESP32!)

Heh, you and everybody else :grin: Unfortunately this one may take a bit longer as I don't have the same input data that I normally generate from for the newer chips. I'm working on some other projects right now but when I come back to this I will try to come up with a path forward.

**Comment by igrr** [comment]
>> The SVD file says the device doesn't have an FPU. Is this correct?

> I believe this is correct; I don't see any mention of one in the Technical Reference Manual. @igrr are you able to confirm this please?

Correct, there is no FPU in ESP32-S2 CPU configuration: https://github.com/espressif/xtensa-overlays/blob/a5ab689f009c89712b0e9d4a3bb06e70b2931fcf/xtensa_esp32s2/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h#L128-L132

> > Is there any reason you've switched to a dash in the device name (ESP32C3 -> ESP32-C3)? Not a big issue, but it needs a small change in TinyGo because basically every other chip family we have some support for doesn't have such a dash.

Sorry about that, that's one on me. We have decided to stick to the two name formats: 1) full marketing names, as presented on the website and in the datasheets (upper case, with a dash), 2) lower case, no dashes — mostly inside code as identifiers and in filenames. We can switch to the lower-case-no-dashes option here if you think this will be a major improvement.

**Comment by aykevl** [comment]
> Sorry about that, that one is on me. We have decided to stick to the two name formats: 1) full marketing names, as presented on the website and in the datasheets (upper case, with a dash), 2) lower case, no dashes — mostly inside code as identifiers and in filenames. We can switch to the lower-case-no-dashes option here if you think this will be a major improvement.

I see. No it's not a big issue, I've simply updated our SVD-to-Go converter to remove dashes from the device name.

**Pull request merged**
